name: Build and release binary

on:
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - '*'
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  build:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.21.0'
      - run: go version
      - run: go mod tidy
      - run: go build -o vault-pki-exporter cmd/main.go
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: vault-pki-exporter