name: Automated tests

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - develop

    # Publish `v1.2.3` tags as releases.
    tags:
      - '*'

  # Run tests for any PRs.
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker compose build

      - name: Download venom
        run: curl https://github.com/ovh/venom/releases/download/v1.1.0/venom.linux-amd64 -L -o /usr/local/bin/venom && chmod +x /usr/local/bin/venom

      - name: Run test
        run: venom run tests.yaml